server:
  port: ${SERVER_PORT}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

randomorg:
  api:
    url: ${RANDOMORG_API_URL}

authservice:
  api:
    url: ${AUTHSERVICE_API_URL}