server:
  port: 4003

spring:
  data:
    mongodb:
      uri: mongodb://mongo:mongo@localhost:27017/paymentdb?authSource=admin
      database: paymentdb

  kafka:
    consumer:
      group-id: payment-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      bootstrap-servers: localhost:29092
      properties:
          spring.json.use.type.headers: false
          spring.json.value.default.type: com.innowise.paymentservice.kafka.consumer.OrderCreatedEvent
          spring.json.trusted.packages: com.innowise.paymentservice.kafka
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

